name: uw_functional_tests

on:
  push:
    branches:
      - main
    paths:
      - universalwrapper/**
      - tests/**
      - tox.ini
      - .github/workflows/main.yml

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      - name: Lint with black
        run: |
          tox -e format
      - name: Run functional tests
        run: |
          tox -e unittest,coverage
